apiVersion: batch/v1
kind: Job # Deployment will automatically restart when killed. Use Pod if not needed
metadata:
  labels:
    k8s-app: research
  generateName: darts-2-noise-aug-kl
  namespace: ecepxie
  name: darts-2-noise-aug-kl
spec:
  template:
    metadata:
      labels:
        k8s-app: research
    spec:
      restartPolicy: Never
      containers:
      - name: research
        image: gitlab-registry.nautilus.optiputer.net/vamsirk/research-containers
        imagePullPolicy: Always
        workingDir: /ceph/darts-parallel/darts_slow
        command: ["/bin/bash","augment.sh"]
        args: ["4", "Genotype(normal=[[('sep_conv_3x3', 0), ('dil_conv_3x3', 1)], [('sep_conv_3x3', 0), ('sep_conv_3x3', 1)], [('dil_conv_5x5', 2), ('sep_conv_3x3', 1)], [('dil_conv_3x3', 3), ('sep_conv_3x3', 2)]], normal_concat=range(2, 6), reduce=[[('max_pool_3x3', 0), ('skip_connect', 1)], [('dil_conv_3x3', 2), ('sep_conv_5x5', 1)], [('dil_conv_5x5', 3), ('avg_pool_3x3', 1)], [('dil_conv_5x5', 3), ('dil_conv_5x5', 2)]], reduce_concat=range(2, 6))"]
        resources:
          requests:
            memory: "6Gi"
            cpu: "4"
            nvidia.com/gpu: 1
          limits:
            memory: "8Gi"
            cpu: "4"
            nvidia.com/gpu: 1
        volumeMounts:
#        - mountPath: /dev/shm
#          name: dshm
        - mountPath: /ceph
          name: kunlin-volume
#      volumes:
#      - name: dshm
#        emptyDir:
#          medium: Memory
#      - name: ceph
#        flexVolume:
#          driver: ceph.rook.io/rook
#          fsType: ceph
#          options:
#            clusterNamespace: rook
#            fsName: nautilusfs
#            path: /ecepxie
#            mountUser: ecepxie
#            mountSecret: ceph-fs-secret
      volumes:
        - name: kunlin-volume
          persistentVolumeClaim:
            claimName: kunlin-volume
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: gpu-type
                operator: In # Use NotIn for other types
                values:
                - 1080Ti
