apiVersion: v1
kind: Pod
metadata:
  name: kunlin
spec:
  containers:
  - name: vol-container
    image: gitlab-registry.nautilus.optiputer.net/vamsirk/research-containers
    command: ["/bin/bash"]
    args: ["-c", "sleep infinity"]
    resources:
      requests:
        memory: "4Gi"
        nvidia.com/gpu: 1
        cpu: 1
      limits:
        nvidia.com/gpu: 1
        memory: "4Gi"
        cpu: 1
    volumeMounts:
    - name: kunlin-volume     #use your own volume path
      mountPath: /kunlin-volume
  restartPolicy: Never
  volumes:
    - name: kunlin-volume
      persistentVolumeClaim:
        claimName: kunlin-volume
