apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kunlin-volume  #use your preferred name
spec:
  storageClassName: rook-cephfs
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1000Gi
