apiVersion: apps/v1
kind: Deployment # Deployment will automatically restart when killed. Use Pod if not needed
metadata:
  labels:
    k8s-app: research
  generateName: master-kl
  namespace: ecepxie
  name: master-kl
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: master-kl
  template:
    metadata:
      labels:
        k8s-app: master-kl
    spec:
      restartPolicy: Always
      containers:
      - name: research
        image: gitlab-registry.nautilus.optiputer.net/vamsirk/research-containers
        imagePullPolicy: Always
        workingDir: /ceph/darts-parallel/ps
        command: ["/bin/bash"]
        args: ["-c", "sleep infinity"]
#        command: ["/bin/bash","run_server.sh"]
#        args: ["2"]
        resources:
          requests:
            memory: "6Gi"
            cpu: "2"
            nvidia.com/gpu: 1
          limits:
            memory: "8Gi"
            cpu: "4"
            nvidia.com/gpu: 1
        volumeMounts:
        - mountPath: /ceph
          name: kunlin-volume
      volumes:
        - name: kunlin-volume
          persistentVolumeClaim:
            claimName: kunlin-volume
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: gpu-type
                operator: In # Use NotIn for other types
                values:
                - 1080Ti
