apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: server-kl
  name: server-kl
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    k8s-app: master-kl
  type: ClusterIP