apiVersion: batch/v1
kind: Job # Deployment will automatically restart when killed. Use Pod if not needed
metadata:
  labels:
    k8s-app: research
  generateName: darts-parallel
  namespace: ecepxie
  name: darts-parallel
spec:
  template:
    metadata:
      labels:
        k8s-app: research
    spec:
      restartPolicy: Never
      containers:
      - name: research
        image: gitlab-registry.nautilus.optiputer.net/vamsirk/research-containers
        imagePullPolicy: Always
        workingDir: /ceph/darts/darts_test
        command: ["/bin/bash","run_darts_parallel.sh"]
        resources:
          requests:
            memory: "64Gi"
            cpu: "6"
            nvidia.com/gpu: 2
          limits:
            memory: "64Gi"
            cpu: "6"
            nvidia.com/gpu: 2
        volumeMounts:
        - mountPath: /dev/shm
          name: dshm
        - mountPath: /ceph
          name: kunlin-volume
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
      - name: kunlin-volume
        persistentVolumeClaim:
          claimName: kunlin-volume
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: gpu-type
                operator: In # Use NotIn for other types
                values:
                - 1080Ti
